### ISSUE TITLE
How to train the images on our own Dataset. 

### ISSUE THREAD

**Issue by krishmadubey** [VPanjeta/Deep-Object-Removal#2]
Can you please specify how can we train the model with our own dataset?

**Comment by VPanjeta** [comment]
Hi @krishmadubey 

The model given is a generalized model so it should work on any type of input but in any case if you wanna fine-tune the weights you'll probably have to write a finetuning script.  
I do not have that in the repo because I haven't written it, but I can tell you how to go about it if you need that.
Although in my opinion, there have been a lot of new advancements in object removal since I wrote this code.
One of the better ones was published in CVPR 2019 called [Pluralistic-Inpainting](https://github.com/lyndonzheng/Pluralistic-Inpainting). They provide a training script as well as pre-trained weights. You can have a look at that as well.

**Comment by krishmadubey** [comment]
Thanks @VPanjeta .

**Comment by krishmadubey** [comment]
Thanks @VPanjeta .
