### ISSUE TITLE
Deleting texts over images

### ISSUE THREAD

**Issue by o7k7** [VPanjeta/Deep-Object-Removal#4]
Hi,
We have tried to maximise pen size to 200 from 20 so that we can use this program to delete text over images.
When we tried to fill a larger body than the max preset pen size we are getting black in the middle of the postprocessed area.
Is this because of a limiter inside the code that doesn’t allow drawn areas to be larger than the max pen size so we get black in the middle but not the perimeter of the drawn area.
Or is it because pre-trained model is trained in such way only small images and small areas to be deleted are used so once we try to draw larger areas to be deleted model doesn’t respond well?
Thank you for your support and creativity generating this code.

[https://ibb.co/W2xcGkH](url)

**Comment by batirayloodos** [comment]
I'm having the same problem if you could help us deleting bigger objects in larger images (min 800x800) I would be appreciated.

**Comment by VPanjeta** [comment]
Hi @o7k7 

Sorry I have been busy and couldn't respond in time. This project was done on a very small dataset and was supposed to be pushed to  a very computationally restrictive machine hence the model is very small. 
Since I pushed this code, there have been a lot of advancements in image inpainting like [Pluralistic Inpainting](https://github.com/lyndonzheng/Pluralistic-Inpainting) which you can try to get far better results.

Closing this for now.
